os:
  - osx
language: ruby
cache: bundler
rvm:
  - 2.3.1
  # OS X 10.9.5-10.10.0 (2.0.0-p481)
  - system
  # OS X 10.9.3-10.9.4
  - 2.0.0-p451

branches:
  only:
    - master

before_install: sudo gem install bundler

addons:
    code_climate:
        repo_token: 6220ef8896c380cb590d4640621d1fc4c0d6d36ccc24d3d818cfba76bbd50014
