os:
  - osx
language: ruby
cache: bundler
rvm:
  - head
  - 2.4.2
  # macOS 10.12
  - 2.0.0-p648
  # macOS 10.11
  - 2.0.0-p645
  # macOS 10.10
  - 2.0.0-p481

branches:
  only:
    - master

before_install: sudo gem install bundler

addons:
    code_climate:
        repo_token: 6220ef8896c380cb590d4640621d1fc4c0d6d36ccc24d3d818cfba76bbd50014
